#!/bin/bash

echo "creating temp folder"

mkdir temp

echo "Moving files into temp"

cp CHANGELOG.md temp/CHANGELOG.md
cp README.md temp/README.md
cp LICENSE temp/LICENSE
cp -r lib/ temp/lib/
cp pubspec.yaml temp/pubspec.yaml
cp -r test/ temp/test/

cd temp && flutter pub publish --dry-run

cd ../ && rm -rf temp/
